apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: myapp
spec:
  containers:
  - name: main-container
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: sidecar-one
    image: busybox:latest
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
  - name: sidecar-two
    image: busybox:latest
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
