apiVersion: v1
kind: Pod
metadata:
  name: quota-mem2-cpu-demo
spec:
  containers:
  - name: quota-mem-cpu-demo-ctr
    image: nginx
    resources:
      limits:
        memory: "500Mi"
        cpu: "800m"
      requests:
        memory: "500Mi"
        cpu: "400m"

