apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"configmap-demo-pod","namespace":"default"},"spec":{"containers":[{"command":["sleep","3600"],"env":[{"name":"PLAYER_INITIAL_LIVES","valueFrom":{"configMapKeyRef":{"key":"player_initial_lives","name":"game-demo"}}},{"name":"UI_PROPERTIES_FILE_NAME","valueFrom":{"configMapKeyRef":{"key":"ui_properties_file_name","name":"game-demo"}}}],"envFrom":[{"configMapRef":{"name":"game-config-env-file"}}],"image":"alpine","name":"demo","volumeMounts":[{"mountPath":"/config","name":"config","readOnly":true}]}],"volumes":[{"configMap":{"items":[{"key":"game.properties","path":"game.properties"},{"key":"user-interface.properties","path":"user-interface.properties"}],"name":"game-demo"},"name":"config"}]}}
  creationTimestamp: "2023-10-02T05:40:20Z"
  name: configmap-demo-pod
  namespace: default
  resourceVersion: "66500"
  uid: 9e28e374-0d48-4ef8-ad3b-9cebe4166a24
spec:
  containers:
  - command:
    - sleep
    - "3600"
    env:
    - name: PLAYER_INITIAL_LIVES
      valueFrom:
        configMapKeyRef:
          key: player_initial_lives
          name: game-demo
    - name: UI_PROPERTIES_FILE_NAME
      valueFrom:
        configMapKeyRef:
          key: ui_properties_file_name
          name: game-demo
    envFrom:
    - configMapRef:
        name: game-config-env-file
    image: alpine
    imagePullPolicy: Always
    name: demo
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /config
      name: config
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-tmq88
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: game.properties
        path: game.properties
      - key: user-interface.properties
        path: user-interface.properties
      name: game-demo
    name: config
  - name: kube-api-access-tmq88
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-10-02T05:40:20Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-10-02T05:40:25Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-10-02T05:40:25Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-10-02T05:40:20Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://aedca0ba1ac3e6c7d10ddb3630eaea9fc7504f150a21c6dcfa454db454daf2c9
    image: alpine:latest
    imageID: docker-pullable://alpine@sha256:eece025e432126ce23f223450a0326fbebde39cdf496a85d8c016293fc851978
    lastState: {}
    name: demo
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-10-02T05:40:24Z"
  hostIP: 192.168.49.2
  phase: Running
  podIP: 10.244.0.8
  podIPs:
  - ip: 10.244.0.8
  qosClass: BestEffort
  startTime: "2023-10-02T05:40:20Z"
