apiVersion: batch/v1
kind: Job
metadata:
  name: randon-error
spec:
  template:
    spec:
      containers:
      - name: random-error
        image: kodekloud/random-error
      restartPolicy: Never
  backoffLimit: 4

