apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: green
  name: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: green
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: green
    spec:
      volumes:
      - name: test
        configMap:
          name: green
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
          - name: test
            mountPath: /usr/share/nginx/html/index.html
            subPath: green.html  
        resources: {}
status: {}
